package pojo;
// Generated Jun 16, 2017 10:22:35 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Company generated by hbm2java
 */
public class Company  implements java.io.Serializable {


     private int companyId;
     private String companyName;
     private String companyLocation;
     private Set<Recruitment> recruitments = new HashSet<Recruitment>(0);

    public Company() {
    }

	
    public Company(int companyId) {
        this.companyId = companyId;
    }
    public Company(int companyId, String companyName, String companyLocation, Set<Recruitment> recruitments) {
       this.companyId = companyId;
       this.companyName = companyName;
       this.companyLocation = companyLocation;
       this.recruitments = recruitments;
    }
   
    public int getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(int companyId) {
        this.companyId = companyId;
    }
    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }
    public String getCompanyLocation() {
        return this.companyLocation;
    }
    
    public void setCompanyLocation(String companyLocation) {
        this.companyLocation = companyLocation;
    }
    public Set<Recruitment> getRecruitments() {
        return this.recruitments;
    }
    
    public void setRecruitments(Set<Recruitment> recruitments) {
        this.recruitments = recruitments;
    }




}


