package pojo;
// Generated Jun 17, 2017 1:34:53 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Company generated by hbm2java
 */
public class Company  implements java.io.Serializable {


     private String companyNo;
     private String companyName;
     private String companyLocation;
     private Set recruitments = new HashSet(0);

    public Company() {
    }

	
    public Company(String companyNo) {
        this.companyNo = companyNo;
    }
    public Company(String companyNo, String companyName, String companyLocation, Set recruitments) {
       this.companyNo = companyNo;
       this.companyName = companyName;
       this.companyLocation = companyLocation;
       this.recruitments = recruitments;
    }
   
    public String getCompanyNo() {
        return this.companyNo;
    }
    
    public void setCompanyNo(String companyNo) {
        this.companyNo = companyNo;
    }
    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }
    public String getCompanyLocation() {
        return this.companyLocation;
    }
    
    public void setCompanyLocation(String companyLocation) {
        this.companyLocation = companyLocation;
    }
    public Set getRecruitments() {
        return this.recruitments;
    }
    
    public void setRecruitments(Set recruitments) {
        this.recruitments = recruitments;
    }




}


