package pojo;
// Generated Jun 16, 2017 10:22:35 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Job generated by hbm2java
 */
public class Job  implements java.io.Serializable {


     private int jobId;
     private String jobName;
     private byte[] jobType;
     private Set<ToEmploy> toEmploys = new HashSet<ToEmploy>(0);
     private Set<Recruitment> recruitments = new HashSet<Recruitment>(0);

    public Job() {
    }

	
    public Job(int jobId) {
        this.jobId = jobId;
    }
    public Job(int jobId, String jobName, byte[] jobType, Set<ToEmploy> toEmploys, Set<Recruitment> recruitments) {
       this.jobId = jobId;
       this.jobName = jobName;
       this.jobType = jobType;
       this.toEmploys = toEmploys;
       this.recruitments = recruitments;
    }
   
    public int getJobId() {
        return this.jobId;
    }
    
    public void setJobId(int jobId) {
        this.jobId = jobId;
    }
    public String getJobName() {
        return this.jobName;
    }
    
    public void setJobName(String jobName) {
        this.jobName = jobName;
    }
    public byte[] getJobType() {
        return this.jobType;
    }
    
    public void setJobType(byte[] jobType) {
        this.jobType = jobType;
    }
    public Set<ToEmploy> getToEmploys() {
        return this.toEmploys;
    }
    
    public void setToEmploys(Set<ToEmploy> toEmploys) {
        this.toEmploys = toEmploys;
    }
    public Set<Recruitment> getRecruitments() {
        return this.recruitments;
    }
    
    public void setRecruitments(Set<Recruitment> recruitments) {
        this.recruitments = recruitments;
    }




}


