package pojo;
// Generated Jun 16, 2017 10:22:35 AM by Hibernate Tools 4.3.1



/**
 * Manager generated by hbm2java
 */
public class Manager  implements java.io.Serializable {


     private int managerId;
     private String password;

    public Manager() {
    }

	
    public Manager(int managerId) {
        this.managerId = managerId;
    }
    public Manager(int managerId, String password) {
       this.managerId = managerId;
       this.password = password;
    }
   
    public int getManagerId() {
        return this.managerId;
    }
    
    public void setManagerId(int managerId) {
        this.managerId = managerId;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


