package pojo;
// Generated Jun 21, 2017 2:22:37 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Recruitment generated by hbm2java
 */
public class Recruitment  implements java.io.Serializable {


     private String recruitmentNo;
     private Company company;
     private Job job;
     private String jobName;
     private String jobDescription;
     private String companyName;
     private Integer recruitingAmout;
     private String skillRequired;
     private Date deadLine;
     private Character type;
     private Integer salary;

    public Recruitment() {
    }

	
    public Recruitment(String recruitmentNo) {
        this.recruitmentNo = recruitmentNo;
    }
    public Recruitment(String recruitmentNo, Company company, Job job, String jobName, String jobDescription, String companyName, Integer recruitingAmout, String skillRequired, Date deadLine, Character type, Integer salary) {
       this.recruitmentNo = recruitmentNo;
       this.company = company;
       this.job = job;
       this.jobName = jobName;
       this.jobDescription = jobDescription;
       this.companyName = companyName;
       this.recruitingAmout = recruitingAmout;
       this.skillRequired = skillRequired;
       this.deadLine = deadLine;
       this.type = type;
       this.salary = salary;
    }
   
    public String getRecruitmentNo() {
        return this.recruitmentNo;
    }
    
    public void setRecruitmentNo(String recruitmentNo) {
        this.recruitmentNo = recruitmentNo;
    }
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
    public Job getJob() {
        return this.job;
    }
    
    public void setJob(Job job) {
        this.job = job;
    }
    public String getJobName() {
        return this.jobName;
    }
    
    public void setJobName(String jobName) {
        this.jobName = jobName;
    }
    public String getJobDescription() {
        return this.jobDescription;
    }
    
    public void setJobDescription(String jobDescription) {
        this.jobDescription = jobDescription;
    }
    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }
    public Integer getRecruitingAmout() {
        return this.recruitingAmout;
    }
    
    public void setRecruitingAmout(Integer recruitingAmout) {
        this.recruitingAmout = recruitingAmout;
    }
    public String getSkillRequired() {
        return this.skillRequired;
    }
    
    public void setSkillRequired(String skillRequired) {
        this.skillRequired = skillRequired;
    }
    public Date getDeadLine() {
        return this.deadLine;
    }
    
    public void setDeadLine(Date deadLine) {
        this.deadLine = deadLine;
    }
    public Character getType() {
        return this.type;
    }
    
    public void setType(Character type) {
        this.type = type;
    }
    public Integer getSalary() {
        return this.salary;
    }
    
    public void setSalary(Integer salary) {
        this.salary = salary;
    }




}


