package pojo;
// Generated Jun 16, 2017 10:22:35 AM by Hibernate Tools 4.3.1



/**
 * Resume generated by hbm2java
 */
public class Resume  implements java.io.Serializable {


     private int resumeId;
     private Student student;
     private String resumeName;
     private Character gender;
     private Integer age;
     private String picPath;
     private String education;
     private String phone;
     private String email;
     private String skills;
     private String expectedJob;

    public Resume() {
    }

	
    public Resume(int resumeId) {
        this.resumeId = resumeId;
    }
    public Resume(int resumeId, Student student, String resumeName, Character gender, Integer age, String picPath, String education, String phone, String email, String skills, String expectedJob) {
       this.resumeId = resumeId;
       this.student = student;
       this.resumeName = resumeName;
       this.gender = gender;
       this.age = age;
       this.picPath = picPath;
       this.education = education;
       this.phone = phone;
       this.email = email;
       this.skills = skills;
       this.expectedJob = expectedJob;
    }
   
    public int getResumeId() {
        return this.resumeId;
    }
    
    public void setResumeId(int resumeId) {
        this.resumeId = resumeId;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public String getResumeName() {
        return this.resumeName;
    }
    
    public void setResumeName(String resumeName) {
        this.resumeName = resumeName;
    }
    public Character getGender() {
        return this.gender;
    }
    
    public void setGender(Character gender) {
        this.gender = gender;
    }
    public Integer getAge() {
        return this.age;
    }
    
    public void setAge(Integer age) {
        this.age = age;
    }
    public String getPicPath() {
        return this.picPath;
    }
    
    public void setPicPath(String picPath) {
        this.picPath = picPath;
    }
    public String getEducation() {
        return this.education;
    }
    
    public void setEducation(String education) {
        this.education = education;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getSkills() {
        return this.skills;
    }
    
    public void setSkills(String skills) {
        this.skills = skills;
    }
    public String getExpectedJob() {
        return this.expectedJob;
    }
    
    public void setExpectedJob(String expectedJob) {
        this.expectedJob = expectedJob;
    }




}


