package pojo;
// Generated Jun 16, 2017 10:22:35 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Student generated by hbm2java
 */
public class Student  implements java.io.Serializable {


     private int studentId;
     private String studentName;
     private String password;
     private Character gender;
     private Integer resumeAmount;
     private String status;
     private Character active;
     private Set<Resume> resumes = new HashSet<Resume>(0);
     private Set<ToEmploy> toEmploys = new HashSet<ToEmploy>(0);

    public Student() {
    }

	
    public Student(int studentId) {
        this.studentId = studentId;
    }
    public Student(int studentId, String studentName, String password, Character gender, Integer resumeAmount, String status, Character active, Set<Resume> resumes, Set<ToEmploy> toEmploys) {
       this.studentId = studentId;
       this.studentName = studentName;
       this.password = password;
       this.gender = gender;
       this.resumeAmount = resumeAmount;
       this.status = status;
       this.active = active;
       this.resumes = resumes;
       this.toEmploys = toEmploys;
    }
   
    public int getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(int studentId) {
        this.studentId = studentId;
    }
    public String getStudentName() {
        return this.studentName;
    }
    
    public void setStudentName(String studentName) {
        this.studentName = studentName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Character getGender() {
        return this.gender;
    }
    
    public void setGender(Character gender) {
        this.gender = gender;
    }
    public Integer getResumeAmount() {
        return this.resumeAmount;
    }
    
    public void setResumeAmount(Integer resumeAmount) {
        this.resumeAmount = resumeAmount;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Character getActive() {
        return this.active;
    }
    
    public void setActive(Character active) {
        this.active = active;
    }
    public Set<Resume> getResumes() {
        return this.resumes;
    }
    
    public void setResumes(Set<Resume> resumes) {
        this.resumes = resumes;
    }
    public Set<ToEmploy> getToEmploys() {
        return this.toEmploys;
    }
    
    public void setToEmploys(Set<ToEmploy> toEmploys) {
        this.toEmploys = toEmploys;
    }




}


