package pojo;
// Generated Jun 16, 2017 10:22:35 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ToEmploy generated by hbm2java
 */
public class ToEmploy  implements java.io.Serializable {


     private int employId;
     private Job job;
     private Student student;
     private String studentName;
     private String jobName;
     private String companyName;
     private String status;
     private Date applyTime;
     private Integer expectedSalary;

    public ToEmploy() {
    }

	
    public ToEmploy(int employId) {
        this.employId = employId;
    }
    public ToEmploy(int employId, Job job, Student student, String studentName, String jobName, String companyName, String status, Date applyTime, Integer expectedSalary) {
       this.employId = employId;
       this.job = job;
       this.student = student;
       this.studentName = studentName;
       this.jobName = jobName;
       this.companyName = companyName;
       this.status = status;
       this.applyTime = applyTime;
       this.expectedSalary = expectedSalary;
    }
   
    public int getEmployId() {
        return this.employId;
    }
    
    public void setEmployId(int employId) {
        this.employId = employId;
    }
    public Job getJob() {
        return this.job;
    }
    
    public void setJob(Job job) {
        this.job = job;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public String getStudentName() {
        return this.studentName;
    }
    
    public void setStudentName(String studentName) {
        this.studentName = studentName;
    }
    public String getJobName() {
        return this.jobName;
    }
    
    public void setJobName(String jobName) {
        this.jobName = jobName;
    }
    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Date getApplyTime() {
        return this.applyTime;
    }
    
    public void setApplyTime(Date applyTime) {
        this.applyTime = applyTime;
    }
    public Integer getExpectedSalary() {
        return this.expectedSalary;
    }
    
    public void setExpectedSalary(Integer expectedSalary) {
        this.expectedSalary = expectedSalary;
    }




}


